### ISSUE TITLE
HHVM does not work with Predis

### ISSUE THREAD

**Issue by zakhenry** [spira/spira#24]
See https://github.com/nrk/predis/issues/254

Until that is resolved, activating HHVM for the fastcgi worker cannot be done. (Activate in ./docker-compose.yml - php container)

``` yml
 php:  
#  image: nglume/docker-hhvm # @todo switch to hhvm when Predis works with hhvm
  image: nglume/docker-phpfpm
  volumes_from:
    - data
  links:
    - db:db
    - redis:redis
    - queue:queue
    - mailcatcher:mailcatcher
  environment:
    - API_PATH=/api
    - XDEBUG_ENABLED=true
  privileged: true
```
